version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-bookstore
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password01
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
