version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-course-reserve
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password01
      POSTGRES_DB: course-reserve
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
